bag_path: /media/xf/Elements1/id4/3/
gnss_topic: /chcnav/devpvt
lidar_topic: /hesai/pandar_points

key_frame:
  thresh_distance: 2.0
  thresh_yaw_degree: 10.0

paths:
  work_dir: "/home/xf/Desktop/catkin_ws/data/test3/"

voxel_filter:
  min_distance: 3.0
  max_distance: 80.0
  min_z: -2.50
  max_z: 30.0
  voxel_size: 0.1

optimization:
  lm:
    verbosity: "ERROR"
    max_iterations: 100
    linear_solver_type: "MULTIFRONTAL_QR"
    lambda_initial: 0.1
    lambda_factor: 3.0
    lambda_upper_bound: 1.0e8
    lambda_lower_bound: 1.0e-9
    relative_error_tol: 0.001
    absolute_error_tol: 0.001

noise:
  odometry:
    rotation_std: 0.01
    translation_std_xy: 0.02
    translation_std_z: 0.04

loop_closure:
  spatial_thresh: 3.0
  max_iter: 50
  min_neighbour_key_diff: 2

gicp:
  correspondence_randomness: 128
  max_correspondence_distance: 0.50
  max_iterations: 128
  transformation_epsilon: 0.001
  rotation_epsilon: 0.001
  initial_lambda_factor: 1.0e-9
